services:
  db:
    image: pgvector/pgvector:pg17
    container_name: rag_pgvector
    environment:
      POSTGRES_DB: ai_rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - rag_pgvector_data:/var/lib/postgresql/data

volumes:
  rag_pgvector_data:
